version: '3.8'

services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: always
    # ports:
    #   - "9099:9099"
    volumes:
      - pipelines:/app/pipelines

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama

volumes:
  pipelines:
  open-webui:
  ollama: